config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  
  resource :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  get 'signup', to: 'users#new'
  resources :learning_resources
  resources :courses do
    resources :course_items
  end

  resources :study_sets do
    member do
      post :add_course
      delete :remove_course
      get :select_courses
    end
    
    resources :learning_plans, only: [:new, :create, :edit, :update, :destroy]
    get 'study', on: :member
  end

  # Study progress tracking
  resources :study_progresses, only: [:update] do
    post :mark_as_studied, on: :member
  end
end

app/models/learning_resource.rb
class LearningResource < ApplicationRecord

  has_many :courses, dependent: :destroy

  validates :title, presence: true

end

app/controllers/learning_resources_controller.rb
class LearningResourcesController < ApplicationController

  before_action :resource, only: [:show, :edit, :update, :destroy]

  def index
    @learning_resources = LearningResource.all
  end

  def show
  end

  def new
    @learning_resource = LearningResource.new
  end

  def create
    @learning_resource = LearningResource.new(learning_resource_params)
    if @learning_resource.save
      redirect_to @learning_resource, notice: "Learning resource was successfully created!"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @learning_resource.update(learning_resource_params)
      redirect_to @learning_resource, notice: "Learning resource was successfully updated!"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @learning_resource.destroy
    redirect_to learning_resources_path, notice: "Learning resource was successfully deleted!"
  end

  private

  def resource 
    @learning_resource = LearningResource.find(params[:id])
  end

  def learning_resource_params
    params.require(:learning_resource).permit(:title, :description, :publisher, :image_url)
  end

end

app/helpers/learning_resources_helper.rb
module LearningResourcesHelper
end

app/views/learning_resources/_form.html.erb
<%= form_with(model: learning_resource) do |f| %>

  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :publisher, class: "form-label" %>
    <%= f.text_field :publisher, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, rows: 4, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :image_url, class: "form-label" %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/learning_resources/edit.html.erb
<div class="container">
  <div class="row p-2 d-flex justify-content-center align-items-center" style="min-height: 80vh;">
      <div class="card col-md-4">
        <div class="card-body">
          <h5>Edit</h5>
          <p>Edit Learning Resource</p>
          <%= render 'form', learning_resource: @learning_resource %>
          <div class="mt-3 mb-3">
        </div>
      </div>
  </div>
</div>

app/views/learning_resources/index.html.erb
<div class="container">
  <div class="row p-2">
    <div class="col-md-12">
      <h1>Leaning Resources</h1>
    </div>
  </div>
  <div class="row align-items-center p-2" >
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Publisher</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      <% @learning_resources.each do |r| %>
        <tr>
          <td><%= link_to r.title, r %></td>
          <td><%= r.publisher %></td>
            <td style="width: 40%"><%= truncate(r.description, length: 25, separator: ' ')%></td>
          <td>
            <%= link_to 'Edit', edit_learning_resource_path(r), class: "btn btn-primary" %>
            <%= link_to 'Delete', learning_resource_path(r), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>

        </tr>
      <% end %>
    </table>
</div>

app/views/learning_resources/new.html.erb
<div class="container">
  <div class="row p-2 d-flex justify-content-center align-items-center" style="min-height: 80vh;">
      <div class="card col-md-4">
        <div class="card-body">
          <h5>Create a Learning Resource</h5>
          <%= render 'form', learning_resource: @learning_resource %>
        </div>
      </div>
  </div>
</div>

app/views/learning_resources/show.html.erb
<div class="container">
  <div class="row p-2">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-2 text-center"><%= @learning_resource.title %></h5>
          <p class="card-subtitle mb-2 text-body-secondary"><%= @learning_resource.description %></p>
          <div class="d-flex flex-row justify-content-around">
            <%= link_to "Update Resource", edit_learning_resource_path(@learning_resource), class: "btn btn-primary" %>
            <%= link_to "Delete Resource", @learning_resource, 
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <h3>Associated Courses</h3>
      <div class="row">
        <% @learning_resource.courses.each do |course| %>
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= course.title %></h5>
                <p class="card-text"><%= course.description %></p>
                <p class="card-text"><small class="text-muted">Type: <%= course.course_type %></small></p>
                <%= link_to "View Course", course_path(course), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>