config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  
  resource :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  get 'signup', to: 'users#new'
  resources :learning_resources
  resources :courses do
    resources :course_items
  end

  resources :study_sets do
    member do
      post :add_course
      delete :remove_course
      get :select_courses
    end
    
    resources :learning_plans, only: [:new, :create, :edit, :update, :destroy]
    get 'study', on: :member
  end

  # Study progress tracking
  resources :study_progresses, only: [:update] do
    post :mark_as_studied, on: :member
  end
end

app/controllers/courses_controller.rb
# app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # 获取所有课程
  def index
    @courses = Course.all
  end

  # 查看单个课程
  def show
    @course_items = @course.course_items
  end

  # 新建课程页面
  def new
    @course = Course.new
  end

  # 创建课程
  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course, notice: '课程创建成功！'
    else
      render :new
    end
  end

  # 编辑课程页面
  def edit
  end

  # 更新课程
  def update
    if @course.update(course_params)
      redirect_to @course, notice: '课程更新成功！'
    else
      render :edit
    end
  end

  # 删除课程
  def destroy
    @course.destroy
    redirect_to courses_url, notice: '课程已删除。'
  end

  private

  # 设置当前课程
  def set_course
    @course = Course.find(params[:id])
  end

  # 允许的参数
  def course_params
    params.require(:course).permit(:title, :description, :type, :learning_resource_id, :user_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class="container">
  <div class="row p-2">
    <div class="col-md-12">
      <h1>Courses</h1>
    </div>
  </div>
  <div class="row align-items-center p-2" >
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Type</th>
          <th>Actions</th>
        </tr>
      <% @courses.each do |r| %>
        <tr>
          <td><%= link_to r.title, r %></td>
          <td style="width: 40%"><%= truncate(r.description, length: 25, separator: ' ')%></td>
          <td><%= r.course_type %></td>
          <td>
            <%= link_to 'Edit', edit_course_path(r), class: "btn btn-primary" %>
            <%= link_to 'Delete', course_path(r), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>

        </tr>
      <% end %>
    </table>
</div>

app/views/courses/show.html.erb
<div class="container">
  <div class="row p-2">
    <div class="col-md-12">
      <h1><%= @course.title %></h1>
      <p><%= @course.description %></p>
    </div>
  </div>
  <div class="row align-items-center p-2" data-controller="course-item" data-course-item-course-id-value="<%= @course.id %>">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Term</th>
          <th>Content</th>
          <th>Actions</th>
        </tr>
      </thead>
      <% @course_items.each do |r| %>
        <tr data-course-item-id-value="<%= r.id %>">
          <td><%= r.term %></td>
          <td>
            <% r.content.values.each do |value| %>
              <%= value %></br>
            <% end %>
          </td>
          <td>
            <button class="btn btn-primary" data-course-item-target="editBtn" data-action="click->course-item#edit">Edit</button>
            <button class="btn btn-danger" data-action="click->course-item#delete" data-course-item-target="deleteBtn">Delete</button>
          </td>
        </tr>
      <% end %>
      <tr data-course-item-target="newItemForm" style="display: none;">
        <td>
          <input type="text" class="form-control" id="newTerm" placeholder="Enter term">
        </td>
        <td>
          <input type="text" class="form-control" id="newContent" placeholder="Enter content">
        </td>
        <td>
          <button class="btn btn-success btn-sm me-2" data-action="click->course-item#saveNew">Save</button>
          <button class="btn btn-secondary btn-sm" data-action="click->course-item#hideNewForm">Cancel</button>
        </td>
      </tr>
    </table>
        <div class="mb-3">
      <button class="btn btn-success" data-course-item-target="addNewBtn" data-action="click->course-item#showNewForm">Add New Item</button>
    </div>
  </div>
</div>