config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  
  resource :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  get 'signup', to: 'users#new'
  resources :learning_resources
  resources :courses do
    resources :course_items
  end

  resources :study_sets do
    member do
      post :add_course
      delete :remove_course
      get :select_courses
    end
    
    resources :learning_plans, only: [:new, :create, :edit, :update, :destroy]
    get 'study', on: :member
  end

  # Study progress tracking
  resources :study_progresses, only: [:update] do
    post :mark_as_studied, on: :member
  end
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-2">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-info mt-2">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger mt-2">
    <%= flash[:error] %>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning mt-2">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="d-flex align-items-center justify-content-center bg-body-tertiary" style="height: 50px;">
  <span>&copy; 2014 Koala Looka</span>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <img src="<%= image_path('logo.png') %>" alt="Koalalooka Logo" height="60" class="d-inline-block align-top">
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active', aria: { current: 'page' } %>
        </li>
        <li class="nav-item">
          <%= link_to "Learning Resources", learning_resources_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Online Apps
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Flashcards</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex gap-2 align-items-center">
        <% if current_user %>
            <%= "Welcome," %>
            <%= link_to current_user.name, user_path(current_user) %>
            <%= link_to "Sign Out", session_path, data: {turbo_method: :delete }, class: "btn btn-primary" %>
        <% else %>
            <%= link_to "Sign In", new_session_path, class: "btn btn-primary" %> 
            <%= link_to "Sign Up", signup_path, class:"btn btn-primary" %> 
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koalalooka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>